### ISSUE TITLE
Tests start failing in nested projects

### ISSUE THREAD

**Issue by pgroot91** [cypress-io/cypress-test-nested-projects#5]
Hi Guys, 

I have trouble to make nested projects to works. Not sure what is wrong but after the first test that is failing other tests seem to hang and the Cypress runner seems to have been freezed after the failed test. 

![image](https://user-images.githubusercontent.com/6934501/63019033-9674f880-be9a-11e9-8e11-0a3ac1a66f5b.png)

With the command-line i'm having the same issue

![image](https://user-images.githubusercontent.com/6934501/63019248-100ce680-be9b-11e9-8650-647ccd037b1a.png)

If i'm running the same tests again with the normal structure of cypress all is good. 
Any suggestions what might be wrong?

Probably it are some off the plugins. Found the code that was causing it.

**cypress/support/index.js**
```
import addContext from 'mochawesome/addContext';

Cypress.on('test:after:run', (test, runnable) => {
  if ('failed' === test.state) {
    const screenshot = window.screenshots.pop();
    const root       = Cypress.config().reporterOptions.reportDir;

    screenshot && addContext({ test }, screenshot.replace(root, ''));
  }
});
``` 

It's probably related to this issue https://github.com/cypress-io/cypress/issues/4536

Regards,
Patrick

**Comment by bahmutov** [comment]
ok, so the reason is in the exception thrown in the callback, not in the nested projects, closing this issue here
