### ISSUE TITLE
QUESTION: `--project` vs. `--config-file`

### ISSUE THREAD

**Issue by jrnail23** [cypress-io/cypress-test-nested-projects#6]
Quick question: what's the difference between using `cypress run --project [MY_PROJECT]` and `cypress run --config-file [MY_CONFIG]`?

**Comment by bahmutov** [comment]
see the answer in https://github.com/cypress-io/cypress-test-nested-projects/pull/7

**Comment by jrnail23** [comment]
Thanks, @bahmutov!
